# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.4.0.schema.json

PackageIdentifier: Cube.CubePlatform
PackageVersion: 3.8.0.1
PackageLocale: zh-HK
Publisher: 方块遊戲
PublisherUrl: https://www.cubejoy.hk
PrivacyUrl: https://pages.cubejoy.com/twprotocol.html
Author: 皖新文化科技有限公司
PackageName: 方块遊戲平台
PackageUrl: https://app.cubejoy.hk/download.html
License: 專有軟件
LicenseUrl: https://pages.cubejoy.com/twprotocol.html
Copyright: 皖新文化科技有限公司版權所有
ShortDescription: 方塊遊戲官方 PC 客戶端軟件
Description: 方塊遊戲官方 PC 客戶端軟件，助您一鍵搞定海量遊戲，智能安裝，更簡單、更快樂！
Tags:
- 商店
- 遊戲
ReleaseNotes: |-
  移除資訊版塊
  修正創建下載任務時崩潰的問題
  修正下載時速度可能一直為 0 的問題
ManifestType: locale
ManifestVersion: 1.4.0
