# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: MPC-BE.MPC-BE
PackageVersion: 1.6.8.5
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
