# Created with WinGet Automation using Komac v1.9.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: AderitoNeto.AfterLife
PackageVersion: 1.0.0
InstallerType: nullsoft
Scope: user
ReleaseDate: 2021-02-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ad3rito/AfterLife/releases/download/1.0.0/AfterLife.Portable.exe
  InstallerSha256: 7007A1CA1EFA01B37A65E9EE68F82EA7CFFFC5421A831F1389B39515F7AB135C
ManifestType: installer
ManifestVersion: 1.4.0
