# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.Edge.Dev
PackageVersion: 117.0.2007.0
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
ProductCode: '{FBA1CBF7-5355-384A-83D8-522989CA126C}'
ReleaseDate: 2023-07-28
Installers:
- Architecture: x86
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/b3a85452-b016-478f-a7e8-4517db7dd362/MicrosoftEdgeDevEnterpriseX64.msi
  InstallerSha256: 2237D45CC7159D5F9846E0EA38A6EB7641E7FA4885F801F30F4E47B147BA4360
- Architecture: x64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/b3a85452-b016-478f-a7e8-4517db7dd362/MicrosoftEdgeDevEnterpriseX64.msi
  InstallerSha256: 2237D45CC7159D5F9846E0EA38A6EB7641E7FA4885F801F30F4E47B147BA4360
- Architecture: arm64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/b3a85452-b016-478f-a7e8-4517db7dd362/MicrosoftEdgeDevEnterpriseX64.msi
  InstallerSha256: 2237D45CC7159D5F9846E0EA38A6EB7641E7FA4885F801F30F4E47B147BA4360
ManifestType: installer
ManifestVersion: 1.4.0
