# Created with YamlCreate.ps1 v2.2.0 using InputObject 🤖 $debug=QUSU.CRLF..7-2-8
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: KristenMcWilliam.Nyrna
PackageVersion: 2.11.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2023-01-31
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Merrit/nyrna/releases/download/v2.11.0/Nyrna-Windows-Installer.exe
  InstallerSha256: 15E534C1FD671A602A577F643ACBAFB14DB17D65DF5C88A4F061E9F71D7AA57C
ManifestType: installer
ManifestVersion: 1.2.0
