# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.Teams.Preview
PackageVersion: 1.6.00.20074
InstallerType: msi
Scope: user
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: install
ProductCode: '{39AF0813-FA7B-4860-ADBE-93B9B214B914}'
ReleaseDate: 2023-07-20
RequireExplicitUpgrade: true
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows/1.6.00.20074/Teams_windows.msi
  InstallerSha256: C08AF6D2FFE440463435A00E247657FFA332E8B75F78F64BF20AFD7354507AF5
  ProductCode: '{39AF0813-FA7B-4860-ADBE-93B9B214B914}'
- Architecture: x64
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.6.00.20074/Teams_windows_x64.exe
  InstallerSha256: C6F0CB12B85377B15D27B3796127FE346292DC117F49BA24334B351A7F8830FB
- Architecture: arm64
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-arm64/1.6.00.20074/Teams_windows_arm64.exe
  InstallerSha256: D1F90174DF2A6D83A979917CC731E964CD64C7D637C1C3AF43D28FA4672B2570
ManifestType: installer
ManifestVersion: 1.4.0
