# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: mmanela.markdownoutlook
PackageVersion: 1.2.0
PackageLocale: en-US
Publisher: Markdown Outlook
PublisherUrl: https://github.com/mmanela
PublisherSupportUrl: https://github.com/mmanela/MarkdownOutlook/issues
PackageName: Markdown Outlook
PackageUrl: https://github.com/mmanela/MarkdownOutlook
License: mit
LicenseUrl: https://github.com/mmanela/MarkdownOutlook/blob/master/License.md
ShortDescription: A simple plugin for Outlook 2013+ which adds a button to the compose mail menu to enable Markdown mode. When enabled your email will be turned from Markdown syntax to html when sending.
Tags:
- email
- mail
- markdown
- microsoft-office
- office
- office-extension
- outlook
ReleaseNotesUrl: https://github.com/mmanela/MarkdownOutlook/releases/tag/v1.2.0
ManifestType: defaultLocale
ManifestVersion: 1.4.0
