# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: IsaqueS.AventurasDeQuintal
PackageVersion: '1.0'
PackageLocale: pt-BR
Publisher: Isaque Sebold de Almeida
PublisherUrl: https://github.com/IsaqueS
PublisherSupportUrl: https://github.com/IsaqueS/Aventuras-de-quintal/issues
PackageName: Aventuras de quintal
PackageUrl: https://github.com/IsaqueS/Aventuras-de-quintal
License: MIT License
LicenseUrl: https://github.com/IsaqueS/Aventuras-de-quintal/blob/main/LICENSE
ShortDescription: Encontre o portal no quintal cheio de aranhas.
ReleaseNotesUrl: https://github.com/IsaqueS/Aventuras-de-quintal/releases/tag/1.0
ManifestType: defaultLocale
ManifestVersion: 1.4.0
