# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: IsaqueS.AventurasDeQuintal
PackageVersion: '1.0'
DefaultLocale: pt-BR
ManifestType: version
ManifestVersion: 1.4.0
