# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: Dogramming.Imaconverter
PackageVersion: imaconverter2.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
