# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Jisco.VisualFamilyTree
PackageVersion: 1.4.0
InstallerType: nullsoft
Scope: user
ReleaseDate: 2021-02-14
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Jisco/VisualFamilyTree/releases/download/v1.4.0/VisualFamilyTree.1.4.0.portable.exe
  InstallerSha256: 374B23F51822488E041C7BC3FF99A66D290FF0A294BC75278A2EA5E007771FD1
ManifestType: installer
ManifestVersion: 1.4.0
