# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Jisco.VisualFamilyTree
PackageVersion: 1.4.0
PackageLocale: en-US
Publisher: Jens Hoernecke
PublisherUrl: https://github.com/Jisco
PublisherSupportUrl: https://github.com/Jisco/VisualFamilyTree/issues
PackageName: Visual Family Tree
PackageUrl: https://github.com/Jisco/VisualFamilyTree
License: Copyright © 2021 Jens Hoernecke
ShortDescription: Create a family tree in a simple and visual way.
ReleaseNotes: |-
  - First release on Mac OSx 🍎
  - Enable import of GEDCOM files 🚀
  - Donation button added to menu ( maybe you will click on it... ) 😅
  - Adding an awesome "what's new" popup (will only show once after each update)
ReleaseNotesUrl: https://github.com/Jisco/VisualFamilyTree/releases/tag/v1.4.0
ManifestType: defaultLocale
ManifestVersion: 1.4.0
