# Created with WinGet Automation using Komac v1.9.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: CometNetwork.BitComet
PackageVersion: '2.01'
PackageLocale: en-US
Publisher: CometNetwork
PublisherUrl: https://www.bitcomet.com/en
PublisherSupportUrl: http://wiki.bitcomet.com
PrivacyUrl: http://wiki.bitcomet.com/privacy_policy
PackageName: BitComet
PackageUrl: https://www.bitcomet.com/en
License: Freeware
LicenseUrl: https://www.bitcomet.com/en/license
Copyright: (C) 2003-2023 BitComet.com
CopyrightUrl: https://www.bitcomet.com/en/copyright
ShortDescription: A free C++ BitTorrent Download Client
Description: BitComet is a free BitTorrent download client which is powerful, super-fast and easy-to-use.
Tags:
- bittorrent
- bt
- download
- magnet
- p2p
- share
- sharing
- torrent
- upload
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: http://wiki.bitcomet.com/frequently_asked_questions
ManifestType: defaultLocale
ManifestVersion: 1.4.0
