# Created with WinGet Automation using Komac v1.9.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: AdoptOpenJDK.OpenJDK.8
PackageVersion: jdk8u292-b10_openj9-0.26.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2021-04-22
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10_openj9-0.26.0/OpenJDK8U-jdk_x86-32_windows_openj9_8u292b10_openj9-0.26.0.msi
  InstallerSha256: B677A0E87EEAB6CB74BAB7C801A29EB3D3C61812A3A77DC666E4442DED5D2E14
  ProductCode: '{B7FC1082-3B65-4E0B-9A59-017D4C74649C}'
- Architecture: x64
  InstallerUrl: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10_openj9-0.26.0/OpenJDK8U-jdk_x64_windows_openj9_8u292b10_openj9-0.26.0.msi
  InstallerSha256: 49E59DDBF8D9BCFFBFE7C02BC4911CCC44B2426DB4F4F02A3C13C3C0DADC28DF
  ProductCode: '{7355976E-4C3F-4D7A-9DEB-E860BE7B0EEB}'
ManifestType: installer
ManifestVersion: 1.4.0
