# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: ArtifexSoftware.GhostScript
PackageVersion: 10.01.2
PackageLocale: en-US
Publisher: Artifex Software Inc.
PublisherUrl: https://artifex.com
PublisherSupportUrl: https://artifex.com/support
Author: Artifex Software Inc.
PackageName: GPL Ghostscript
PackageUrl: https://www.ghostscript.com
License: AGPL-3.0-or-later | Freeware
LicenseUrl: https://www.gnu.org/licenses/agpl-3.0.html
CopyrightUrl: https://www.gnu.org/licenses/agpl-3.0.html
ShortDescription: An interpreter for the PostScript language and for PDF.
Moniker: ghostscript
Tags:
- pdf
- pdf-tools
- postscript
ReleaseNotesUrl: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/tag/gs10012
ManifestType: defaultLocale
ManifestVersion: 1.4.0
