# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: ElectronCommunity.ElectronFiddle
PackageVersion: 0.33.0
PackageLocale: en-US
Publisher: Electron Community
PublisherUrl: https://www.electronjs.org
PublisherSupportUrl: https://github.com/electron/fiddle/issues
PrivacyUrl: https://openjsf.org/wp-content/uploads/sites/84/2021/04/OpenJS-Foundation-Privacy-Policy-2019-11-15.pdf
Author: Electron Community
PackageName: Electron Fiddle
PackageUrl: https://electronjs.org/fiddle
License: MIT
LicenseUrl: https://github.com/electron/fiddle/blob/master/LICENSE.md
Copyright: Copyright (c) 2021 Electron Community
ShortDescription: The easiest way to get started with Electron
Tags:
- electron
- fiddle
ReleaseNotes: |-
  What's Changed
  - build(deps): bump semver from 7.3.5 to 7.5.2 by @dependabot in #1377
  - build: lock @electron-forge/* versions at 6.1.1 by @dsanders11 in #1381
  - fix: update settings in all open windows by @erikian in #1376
  - chore: update to Electron 25.2.0 by @dsanders11 in #1383
  - fix: await loadTheme in app setup by @dsanders11 in #1382
  - feat: support AppImage releases by @robertgzr in #1379
  - build: cleanup package.json dependencies by @dsanders11 in #1380
  - chore: use node: scheme prefix for imports by @dsanders11 in #1385
  - test: ugrade jest by @dsanders11 in #1387
  - chore: clean up use of any typings by @dsanders11 in #1388
  - perf: import modules in parallel during app setup by @dsanders11 in #1384
  - ci: simplify publish job requires by @dsanders11 in #1390
  - fix: improve behavior of setting sync between windows by @dsanders11 in #1386
  - chore: release v0.33.0 by @dsanders11 in #1396
  New Contributors
  - @erikian made their first contribution in #1376
  - @robertgzr made their first contribution in #1379
ReleaseNotesUrl: https://github.com/electron/fiddle/releases/tag/v0.33.0
ManifestType: defaultLocale
ManifestVersion: 1.4.0
