# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: ElectronCommunity.ElectronFiddle
PackageVersion: 0.33.0
InstallerLocale: en-US
InstallerType: exe
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
FileExtensions:
- html
- js
ReleaseDate: 2023-07-12
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/electron/fiddle/releases/download/v0.33.0/electron-fiddle-0.33.0-win32-ia32-setup.exe
  InstallerSha256: A554B7F02EAB745B276E9AECD3DB666F4D033D4799D2809E2EBE5FB31284EC48
- Architecture: x64
  InstallerUrl: https://github.com/electron/fiddle/releases/download/v0.33.0/electron-fiddle-0.33.0-win32-x64-setup.exe
  InstallerSha256: 95D25032236A7DA5BEE2A9296C1FF343AE0B2C5BCFC54364C973D5497B51013B
ManifestType: installer
ManifestVersion: 1.4.0
