# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.Edge
PackageVersion: 115.0.1901.188
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- msedge
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
ProductCode: '{9534CC0C-0400-3359-973B-C0287868D2E4}'
ReleaseDate: 2023-07-27
Installers:
- Architecture: x86
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/ff48a0f9-8b02-46c9-bbbc-9c5f9a94b67d/MicrosoftEdgeEnterpriseX86.msi
  InstallerSha256: BAFE7CF14A2190C1AE85C883CBD671D444A64741DA23FD7230A62A69F7972408
- Architecture: x64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/ff48a0f9-8b02-46c9-bbbc-9c5f9a94b67d/MicrosoftEdgeEnterpriseX86.msi
  InstallerSha256: BAFE7CF14A2190C1AE85C883CBD671D444A64741DA23FD7230A62A69F7972408
- Architecture: arm64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/ff48a0f9-8b02-46c9-bbbc-9c5f9a94b67d/MicrosoftEdgeEnterpriseX86.msi
  InstallerSha256: BAFE7CF14A2190C1AE85C883CBD671D444A64741DA23FD7230A62A69F7972408
ManifestType: installer
ManifestVersion: 1.4.0
