# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Jaquadro.NBTExplorer
PackageVersion: 2.8.0-win
PackageLocale: en-US
Publisher: Justin Aquadro
PublisherUrl: https://github.com/jaquadro
PublisherSupportUrl: https://github.com/jaquadro/NBTExplorer/issues
PackageName: NBTExplorer
PackageUrl: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac
License: MIT License
LicenseUrl: https://github.com/jaquadro/NBTExplorer/blob/master/LICENSE.txt
ShortDescription: A graphical NBT editor for all Minecraft NBT data sources.
ReleaseNotes: '- New: Support for NBT long array tags'
ReleaseNotesUrl: https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win
ManifestType: defaultLocale
ManifestVersion: 1.4.0
