# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: mentebinaria.retoolkit
PackageVersion: '2023.05'
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /VERYSILENT /NORESTART /COMPONENTS="*android,*autoit,*calculators,*cobaltstrike,*debuggers,*decompilers,*delphi,*dotnet,*elf,*go,*hexeditors,*java,*ole,*network,*pdf,*pe,*peresourceeditors,*processinspection,*programming,*signature,*systeminformation,*unpacking,*utilities,!network\nmap"
  SilentWithProgress: /SILENT /NORESTART /COMPONENTS="*android,*autoit,*calculators,*cobaltstrike,*debuggers,*decompilers,*delphi,*dotnet,*elf,*go,*hexeditors,*java,*ole,*network,*pdf,*pe,*peresourceeditors,*processinspection,*programming,*signature,*systeminformation,*unpacking,*utilities,!network\nmap"
UpgradeBehavior: install
Commands:
- bazzar
- capa
- CobaltStrikeScan
- d2j-dex2jar
- de4dot
- DisView
- floss
- hollows_hunter
- manw
- OfficeMalScanner
- pe-sieve
- redress
- RTFScan
- upx
- vt
- winapiexec
ProductCode: '{BB46345D-F5E9-408E-AA39-64A5EDD92E30}_is1'
ReleaseDate: 2023-05-31
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mentebinaria/retoolkit/releases/download/2023.05/retoolkit_2023.05_setup.exe
  InstallerSha256: 1EB3511E8B816641D3EE6686BFC61329B54532BFD5CD8A65AA20F154EE55D120
ManifestType: installer
ManifestVersion: 1.4.0
