# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.WingetCreate
PackageVersion: 1.2.8.0
InstallerLocale: en-US
Platform:
- Windows.Universal
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- wingetcreate
PackageFamilyName: Microsoft.WindowsPackageManagerManifestCreator_8wekyb3d8bbwe
ReleaseDate: 2023-07-19
Installers:
- Platform:
  - Windows.Universal
  Architecture: x86
  InstallerType: msix
  Scope: user
  InstallerUrl: https://github.com/microsoft/winget-create/releases/download/v1.2.8.0/wingetcreate.exe
  InstallerSha256: DE4C553F33A9E6E5B537BF2C969E3A764BA5E04EB11E4D22B6D9A0F38D22D95A
  UpgradeBehavior: install
  PackageFamilyName: Microsoft.WindowsPackageManagerManifestCreator_8wekyb3d8bbwe
- Architecture: x86
  InstallerType: portable
  InstallerUrl: https://github.com/microsoft/winget-create/releases/download/v1.2.8.0/wingetcreate.exe
  InstallerSha256: DE4C553F33A9E6E5B537BF2C969E3A764BA5E04EB11E4D22B6D9A0F38D22D95A
- Platform:
  - Windows.Universal
  Architecture: x64
  InstallerType: msix
  Scope: user
  InstallerUrl: https://github.com/microsoft/winget-create/releases/download/v1.2.8.0/wingetcreate.exe
  InstallerSha256: DE4C553F33A9E6E5B537BF2C969E3A764BA5E04EB11E4D22B6D9A0F38D22D95A
  UpgradeBehavior: install
  PackageFamilyName: Microsoft.WindowsPackageManagerManifestCreator_8wekyb3d8bbwe
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/microsoft/winget-create/releases/download/v1.2.8.0/wingetcreate.exe
  InstallerSha256: DE4C553F33A9E6E5B537BF2C969E3A764BA5E04EB11E4D22B6D9A0F38D22D95A
ManifestType: installer
ManifestVersion: 1.4.0
