# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Hirschmann.NotebookFanControl
PackageVersion: 1.6.3
PackageLocale: en-US
Publisher: Stefan Hirschmann - StagWare
PublisherUrl: https://github.com/hirschmann/nbfc
PublisherSupportUrl: https://github.com/hirschmann/nbfc/issues
Author: Hirschmann
PackageName: NoteBook FanControl
PackageUrl: https://github.com/hirschmann/nbfc
License: GNU General Public License v3.0
LicenseUrl: https://raw.githubusercontent.com/hirschmann/nbfc/master/LICENSE.md
Copyright: Copyright 2007 Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/hirschmann/nbfc/master/LICENSE.md
ShortDescription: NBFC is a cross-platform fan control service for notebooks. It comes with a powerful configuration system, which allows to adjust it to many different notebook models.
Description: NBFC is a cross-platform fan control service for notebooks. It comes with a powerful configuration system, which allows to adjust it to many different notebook models.
Moniker: notebook-fancontrol
Tags:
- notebook
- fan
- control
- nbfc
- temperature
ReleaseNotes: |-
  - Support for Intel CoffeeLake, ApolloLake and AMD Ryzen CPUs (thanks @dan-and)
  - Support for AMD Puma CPUs
  - Support for many new notebook models
  - ec-probe now supports colored output
  - Improved settings file handling
  - Lots of stability improvements and bugfixes
ReleaseNotesUrl: https://github.com/hirschmann/nbfc/releases/tag/1.6.3
ManifestType: defaultLocale
ManifestVersion: 1.4.0
