# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.Teams
PackageVersion: 1.6.00.18681
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: install
ReleaseDate: 2023-07-06
RequireExplicitUpgrade: true
Installers:
- Architecture: x86
  InstallerType: msi
  Scope: user
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows/1.6.00.18681/Teams_windows.msi
  InstallerSha256: 79021CD75CC38AB40F8CD2103EEF8A283A9013AA0A1B45BD74BBE554109DBD3E
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
  ProductCode: '{39AF0813-FA7B-4860-ADBE-93B9B214B914}'
  AppsAndFeaturesEntries:
  - ProductCode: Teams
- Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows/1.6.00.18681/Teams_windows.msi
  InstallerSha256: 79021CD75CC38AB40F8CD2103EEF8A283A9013AA0A1B45BD74BBE554109DBD3E
  ProductCode: '{39AF0813-FA7B-4860-ADBE-93B9B214B914}'
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.6.00.18681/Teams_windows_x64.exe
  InstallerSha256: D71AECE8257FC268B36610C3DBA8311AFA564E576140AD80DD2518A7BFB4252D
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
  AppsAndFeaturesEntries:
  - ProductCode: Teams
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.6.00.18681/Teams_windows_x64.exe
  InstallerSha256: D71AECE8257FC268B36610C3DBA8311AFA564E576140AD80DD2518A7BFB4252D
  ProductCode: '{731F6BAA-A986-45A4-8936-7C3AAAAA760B}'
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-arm64/1.6.00.18681/Teams_windows_arm64.exe
  InstallerSha256: 4F6910E47494741C1024AE317BABB323CE2642D619940C6CC6A5E9DE5E1BFE2B
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
  ProductCode: '{39AF0813-FA7B-4860-ADBE-93B9B214B914}'
- Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-arm64/1.6.00.18681/Teams_windows_arm64.exe
  InstallerSha256: 4F6910E47494741C1024AE317BABB323CE2642D619940C6CC6A5E9DE5E1BFE2B
  ProductCode: '{C082BDFE-B874-4543-B507-CDFD6F23EFF0}'
ManifestType: installer
ManifestVersion: 1.4.0
