# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: deep5050.qikQR
PackageVersion: 1.0.0
InstallerType: nullsoft
ReleaseDate: 2020-05-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/deep5050/qikQR/releases/download/v1.0.0/qikqr-1.0.0.exe
  InstallerSha256: 59E43A97E03E778C28F56835241A420397ADB3BA1F826D94C4786F46F7CD2EB3
ManifestType: installer
ManifestVersion: 1.4.0
