# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: deep5050.qikQR
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: dipankar Pal
PublisherUrl: https://github.com/deep5050
PublisherSupportUrl: https://github.com/deep5050/qikQR/issues
PackageName: qikqr
PackageUrl: https://github.com/deep5050/qikQR
License: MIT
LicenseUrl: https://github.com/deep5050/qikQR/blob/master/LICENSE
ShortDescription: simple app to create QR codes
ReleaseNotesUrl: https://github.com/deep5050/qikQR/releases/tag/v1.0.0
ManifestType: defaultLocale
ManifestVersion: 1.4.0
