# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: DavidWheatley.fs2020-livery-manager
PackageVersion: 0.5.3
PackageLocale: en-US
Publisher: David Wheatley
PublisherUrl: https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager
PublisherSupportUrl: https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/issues
Author: David Wheatley
PackageName: Liveries Mega Pack Manager
PackageUrl: https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager
License: No license
LicenseUrl: https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/blob/main/LICENSE.md
Copyright: © Copyright 2020 David Wheatley and Jaap Rodenburg - All rights reserved
CopyrightUrl: https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/blob/main/LICENSE.md
ShortDescription: A simple, extensible livery manager for Microsoft Flight Simulator
ReleaseNotes: |-
  Added
  - Fixed a bug where the downloadprocess halts in process unpacking if the livery is not existing but the process downloads the errorpage as zip file.
ReleaseNotesUrl: https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/releases/tag/v0.5.3
ManifestType: defaultLocale
ManifestVersion: 1.4.0
