# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: DavidWheatley.fs2020-livery-manager
PackageVersion: 0.5.3
InstallerType: msi
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
ProductCode: '{81A989EC-38F0-4057-985F-441666E111CA}'
ReleaseDate: 2022-01-10
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/releases/download/v0.5.3/Liveries_Mega_Pack_Manager-0.5.3-setup.msi
  InstallerSha256: 794351712AB610D42189E29BC373B3806B742D34A5F3D11351B796AFFEFF0C67
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/releases/download/v0.5.3/Liveries_Mega_Pack_Manager-0.5.3-setup.msi
  InstallerSha256: 794351712AB610D42189E29BC373B3806B742D34A5F3D11351B796AFFEFF0C67
  UpgradeBehavior: uninstallPrevious
ManifestType: installer
ManifestVersion: 1.4.0
