# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: n457.uncolored
PackageVersion: .0.10.2
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
FileExtensions:
- html
- md
ReleaseDate: 2016-11-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/n457/Uncolored/releases/download/v.0.10.2/Uncolored-v.0.10.2-win-x64-setup.exe
  InstallerSha256: 0B141B4B9FA44F3342740A4058C462B45D50F9EFE29D4B54DDA60250A979CF76
ManifestType: installer
ManifestVersion: 1.4.0
