# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Jellyfin.Server
PackageVersion: 10.8.10
InstallerType: nullsoft
ReleaseDate: 2023-04-23
Installers:
- Architecture: x64
  InstallerUrl: https://repo.jellyfin.org/releases/server/windows/stable/installer/jellyfin_10.8.10_windows-x64.exe
  InstallerSha256: 76CC7B43F806380C3F8FA8DBE7AB93173794D84B2A6C095703EB0B3DEBB8B23D
ManifestType: installer
ManifestVersion: 1.4.0
